version: '3.5'
services:
  db:
    container_name: Ersatzteil-DB
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/data:/var/lib/postgresql/data